### ISSUE TITLE
python-bitcoinrpc not in PyPi

### ISSUE THREAD

**Issue by xsleonard** [jgarzik/python-bitcoinrpc#26]
This cannot be installed with pip (python package & dependency manager) since it is not in PyPi.  

The ability to register the package with pypi was added in this pull request:
https://github.com/jgarzik/python-bitcoinrpc/pull/7

All that should be needed is mentioned in that pull request, specifically
`python setup.py register sdist upload`

**Comment by gustavklopp** [comment]
pip version is buggy:
try to run `rpc_connection.getnewaddress()` returns `None` because of a missing `return response['result']`...

**Comment by nmarley** [comment]
This exists now and is current as of today:

https://pypi.python.org/pypi/python-bitcoinrpc/

This issue can be closed.
