### ISSUE TITLE
RPC SSL to btcd

### ISSUE THREAD

**Issue by PRabahy** [jgarzik/python-bitcoinrpc#35]
I am trying to use bitcoind-ncurses to connect to btcd. I successfully got bitcoind-ncurses running on my box and had to make a small mod to it for it to support SSL (https://github.com/PRab/bitcoind-ncurses/commit/d49a8c4c3ec6b77b2a277b7ac4af763560684a8a). Even after doing that, I am having trouble getting to to connect.

I am very inexperience with python so began adding print statements to the code and believe I have the bug narrowed down to authproxy.py --> **call** --> self.__conn.request(...). I see that it makes the call, but never executes the print statement that I added on the next line. I assume that this means that it threw an exception.

I was suspicious of the call to httplib.HTTPSConnection(...) because it was passing None for the cert and key, but even after adding those it is still skipping my print statement.

I would love to eliminate some variables, but I am also having trouble getting bitcoind to run with RPC SSL and btcd requires RPC SSL (no option for insecure).

**Comment by arnuschky** [comment]
Described fix did not work for me on Ubuntu 12.04, with any python version (2.7.9, for example). See PR #50 for a fix.
