### ISSUE TITLE
Merge downstream

### ISSUE THREAD

**Issue by MarcoFalke** [jgarzik/python-bitcoinrpc#57]
Stuff happened down @ https://github.com/bitcoin/bitcoin . Are you planning to cherry-pick from bitcoin?

**Comment by jgarzik** [comment]
It sounded like those were add-on decorators and modules, not directly applicable here.

Is that wrong?  Are there changes you see that are needed here?

**Comment by MarcoFalke** [comment]
The only one would be https://github.com/bitcoin/bitcoin/commit/ddf98d1d84343f2db0502a85628ef80f2ec57dbd I guess. But there's a conflict in the cherry-pick and I didn't evaluate if it makes sense to have it here.
