### ISSUE TITLE
if there's no login and password 

### ISSUE THREAD

**Issue by GildedHonour** [jgarzik/python-bitcoinrpc#70]
if there's no login and password, how can I use this?

    rpc_connection = AuthServiceProxy("http://%s:%s@127.0.0.1:8332"%(rpc_user, rpc_password))

passing None doesn't work.

**Comment by nikcub** [comment]
The client doesn't support not sending an auth header. Try '' and '' as values (None is string cast as 'None') and it it doesn't work just set a username and password on the daemon

**Comment by jgarzik** [comment]
This proxy is built assuming auth is required, as it is for the use cases designed
