### ISSUE TITLE
OSError: [Errno 113] No route to host

### ISSUE THREAD

**Issue by smatiush** [jgarzik/python-bitcoinrpc#89]
hi 
i have a windows pc in my lan (i have a qt-wallet installed and running),  when i try to do a getinfo call from my laptop it give me this "OSError: [Errno 113] No route to host" but it's online how can i resolve this?
i set a "server=1" parameter and rpcallowip=<myip> in bitcoin.conf

**Comment by jgarzik** [comment]
https://www.maketecheasier.com/fix-no-route-to-host-error-linux/
